### ISSUE TITLE
Please help with igpu

### ISSUE THREAD

**Issue by maej72** [oniksfly/DualBoot-Hackintosh-i7-GA-Z170X-Gaming-5#1]
Thank you very much for sharing you configuration, it helps a lot.

I just have a problem  switching to using the igpu as the main display driver since I have a Nvidia GTX 1650 super which is not supported on macOS.

Can you help me configure it to use the igpu and ignore the Nvidia card without taking it out of the case please?

And can you please share your motherboard bios setting?

(:

**Comment by oniksfly** [comment]
HI! I had unsupported NVIDIA gtx before and to solve this issue I changed card to AMD. So I can't help with it :( 

BIOS settings:

![tempImage2WlHwW-min](https://user-images.githubusercontent.com/5785870/109791487-8dd24780-7c23-11eb-89f4-0e6bc6bc32b4.jpg)
![tempImageejXlte-min](https://user-images.githubusercontent.com/5785870/109791560-a0e51780-7c23-11eb-9ad9-291a73326448.jpg)
![tempImageeTPNYn-min](https://user-images.githubusercontent.com/5785870/109791572-a3e00800-7c23-11eb-899b-bc7a6a742f08.jpg)
![tempImageHhEDHn-min](https://user-images.githubusercontent.com/5785870/109791575-a5113500-7c23-11eb-8dd7-f9cef1e92b54.jpg)
![tempImagejbaPe0-min](https://user-images.githubusercontent.com/5785870/109791581-a6426200-7c23-11eb-85ec-a8dba2e63006.jpg)
![tempImageKr4udf-min](https://user-images.githubusercontent.com/5785870/109791584-a6daf880-7c23-11eb-97cd-ec045ddc07ae.jpg)
![tempImagekRjNit-min](https://user-images.githubusercontent.com/5785870/109791585-a7738f00-7c23-11eb-831c-6f35ecfd4be1.jpg)
![tempImagelH6LSA-min](https://user-images.githubusercontent.com/5785870/109791587-a80c2580-7c23-11eb-9eda-45da425acaa0.jpg)
![tempImagelThh5C-min](https://user-images.githubusercontent.com/5785870/109791590-a80c2580-7c23-11eb-965b-c2590833f960.jpg)
![tempImageQkwBCZ-min](https://user-images.githubusercontent.com/5785870/109791591-a8a4bc00-7c23-11eb-9e2e-45bf886cff91.jpg)
![tempImageSkAVBE-min](https://user-images.githubusercontent.com/5785870/109791593-a93d5280-7c23-11eb-91ff-61f34cefd0f8.jpg)
![tempImagexivLFq-min](https://user-images.githubusercontent.com/5785870/109791594-a93d5280-7c23-11eb-9a78-5fd9463b8375.jpg)

**Comment by maej72** [comment]
WOW Thank you so much, much appreciated <3
